<?php ?>



<h3>Block Module Fix: Offscreen Headers</h3>
<ul>
<li>Functional Goal: Allow authors to select which block headers are not visible and tag those with class "element-invisible"</li>
<li>Related Modules: <a href="http://drupal.org/project/a11y_titles">A11y Titles</a></li>
<li>D8 Issues:</li>
</ul>


<h3>Block Module Fix: Fixed ARIA Roles</h3>
<ul>
<li>Functional Goal: Set known aria roles (such as role="navigation" in menu block) without author intervention.</li>
<li>Related Modules:</li>
<li>D8 Issues: <a href="http://drupal.org/node/1183042">Add WAI-ARIA roles to Core Blocks</a></li>
</ul>
