<?php
/**
 * @file
 * Extend the image module.
 *
 * Extended functionalities
 *   Supported entity types are node, comment and taxonomy term.
 *   - Add checkboxes to the content types image field edit form.
 *     - "Alt field required"
 *     - "Title field required"
 *   - Set the alt text field maxlength value on node edit forms to 128.
 */

/**
 * Implements hook_field_info_alter().
 */
function eim_field_info_alter(&$info) {
  if (isset($info['image'])) {
    $info['image']['instance_settings']['alt_field_required'] = 0;
    $info['image']['instance_settings']['title_field_required'] = 0;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add checkboxes to the content types image field edit form.
 *   - "Alt field required"
 *   - "Title field required"
 */
function eim_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#field']['module'] != 'image') {
    return;
  }

  // Uncompressed version: eim.module.js
  drupal_add_js(drupal_get_path('module', 'eim') . '/js/eim.module.min.js', array('scope' => 'footer'));

  $instance = $form['#instance'];
  $settings = $form['#instance']['settings'];

  if ($instance['entity_type'] == 'node' || $instance['entity_type'] == 'comment' || $instance['entity_type'] == 'taxonomy_term') {
    $form['instance']['settings']['alt_field_required'] = array(
      '#type' => 'checkbox',
      '#title' => t('<em>Alt</em> field required'),
      '#default_value' => $settings['alt_field_required'],
      '#weight' => $form['instance']['settings']['alt_field']['#weight'] + .1,
      '#states' => array(
        'visible' => array(
          'input[name="instance[settings][alt_field]"]' => array('checked' => TRUE)
        )
      )
    );
    $form['instance']['settings']['title_field_required'] = array(
      '#type' => 'checkbox',
      '#title' => t('<em>Title</em> field required'),
      '#default_value' => $settings['title_field_required'],
      '#weight' => $form['instance']['settings']['title_field']['#weight'] + .1,
      '#states' => array(
        'visible' => array(
          'input[name="instance[settings][title_field]"]' => array('checked' => TRUE)
        )
      )
    );
  }
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * Add a #process callback to the imagefield widget element so we
 * can perform alters.
 * See http://drupal.org/node/887424
 */
function eim_field_widget_image_image_form_alter(&$element, &$form_state, $context) {
  foreach (element_children($element) as $delta){
    $element[$delta]['#process'][] = 'eim_imagefield_widget_process';
  }
}

/**
 * Element #process callback function.
 * 
 * Action to
 *   - make alt and title field per content typeas required
 *   - alter the maxlength value of image alt fields for all content types
 * 
 * @see eim_field_widget_image_image_form_alter()
 */
function eim_imagefield_widget_process($element, &$form_state, $form) {
  $instance = field_info_instance($element['#entity_type'], $element['#field_name'], $element['#bundle']);

  if ($instance['settings']['alt_field_required'] == 1) {
    $element['alt']['#required'] = TRUE;
  }
  if ($instance['settings']['title_field_required'] == 1) {
    $element['title']['#required'] = TRUE;
  }
  
  $element['alt']['#maxlength'] = 128;
  
  return $element;
}
